export const PRODUCTS = [
  { id: 1, name: "Pixel 7a", category: "phone", price: 499 },
  { id: 2, name: "Samsung Galaxy A54", category: "phone", price: 399 },
  { id: 3, name: "iPhone 13", category: "phone", price: 799 },
  { id: 4, name: "Dell Inspiron 15", category: "laptop", price: 699 },
  { id: 5, name: "MacBook Air M2", category: "laptop", price: 1199 },
  { id: 6, name: "HP Pavilion", category: "laptop", price: 599 },
  { id: 7, name: "Nike T-Shirt", category: "clothing", price: 35 },
  { id: 8, name: "Levi's Jeans", category: "clothing", price: 89 },
  { id: 9, name: "Adidas Hoodie", category: "clothing", price: 65 },
  { id: 10, name: "Puma Sneakers", category: "clothing", price: 120 },
  { id: 11, name: "IKEA Desk", category: "furniture", price: 299 },
  { id: 12, name: "Office Chair", category: "furniture", price: 199 },
  { id: 13, name: "Bookshelf", category: "furniture", price: 149 },
  { id: 14, name: "Harry Potter Book Set", category: "books", price: 59 },
  { id: 15, name: "The Alchemist", category: "books", price: 15 },
  { id: 16, name: "Atomic Habits", category: "books", price: 18 },
  { id: 17, name: "Yoga Mat", category: "sports", price: 29 },
  { id: 18, name: "Dumbbells Set", category: "sports", price: 89 },
  { id: 19, name: "Tennis Racket", category: "sports", price: 120 },
  { id: 20, name: "Organic Green Tea", category: "food", price: 12 },
  { id: 21, name: "Protein Powder", category: "food", price: 45 },
  { id: 22, name: "Dark Chocolate Box", category: "food", price: 8 }
];
